kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
     matchLabels: 
       app: backend
       tier: backend
       project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec: 
      containers:
      - name: backend
        image: sudhanaga1002/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend 
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080                          